#!/bin/sh
#
# pollinate: an Entropy-as-a-Service client
#
#  Copyright (C) 2012-2016 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -f
DEVICE="/dev/urandom"
PKG="pollinate"
FLAG="/var/cache/pollinate/seeded"

	# Whiten input with a hash, and write to device
	qrandom --hex --min 64 --max 64 | head -c "64" | sha512sum | awk '{print $1}' > "${DEVICE}"
	echo "client successfully seeded [${DEVICE}] from ANU Quantum Server"
	timestamp=$(stat -c "%y" "${FLAG}")
	echo "system was previously seeded at [${timestamp}]"
